Update patch set 1
Patch Set 1:

In the meantime I did a test with the image and your change. 
Result: It fails at startup. See related part of the karaf.log below.

To have here an idea what you are planning I like to use this page in confluence: https://wiki.onap.org/pages/viewpage.action?pageId=84666327 please add here some details about your plan, how to include a1-adapter into sdnc-image.

In SDNC there are "A1-Adapter" related pieces. One (per this change) in onap/sdnc-image and in onap/ccsdk-odlsli-alpine-image there is also some "a1-..". 
At the moment you add the "feature" to SDNC with version 1.0.0-SNAPSHOT. 
SDNC is importing the "odlsli" with version 1.0.0. 
My question: What is your plan here? 1. Adding all new via "ccsdk/oran" repo or 2. using "ccsdk/features"sdnr northbound A1-Adapter?

By the way: We are working at the moment to move all ccsdk related pieces in sdnc-image to version 1.0.1-SNAPSHOT. This is the next develoment version, because 1.0.0 is released now. So you should user version 1.0.1-SNAPSHOT.

karaf.log: 

2020-08-19T08:26:33,652 | ERROR | activator-1-thread-2 | BootFeaturesInstaller            | 9 - org.apache.karaf.features.core - 4.2.6 |  -  | Error installing boot features                                                 
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=a1-adapter-northbound; type=karaf.feature; version="[1.0.0.SNAPSHOT,1.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=a1-adapt
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343) ~[?:?]                                                                                                                                          
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392) ~[?:?]                                                                                                                                                           
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378) ~[?:?]                                                                                                                                                                   
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332) ~[?:?]                                                                                                                                    
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257) ~[?:?]                                                                                                             
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393) ~[?:?]                                                                                                                                                           
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062) ~[?:?]                                                                                                                               
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998) ~[?:?]                                                                                                        
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]                                                                                                                                                                                 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]                                                                                                                           
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]                                                                                                                              
        at java.lang.Thread.run(Thread.java:748) [?:?]                                                                                                                                                                                                    
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve a1-adapter-northbound/1.0.0.SNAPSHOT: missing requirement [a1-adapter-northbound/1.0.0.SNAPSHOT] osgi.identity; osgi.identity=a1-adapter-feature; type=karaf.feature; versi
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343) ~[?:?]

Patch-set: 1
Reviewer: Gerrit User 4931 <4931@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>

Former-commit-id: 61cc512132d6dbef6c46a3ca25eb6077f3ced0dd